/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pet;

import java.awt.Color;

/**
 *
 * @author me
 */
public class petMenu extends javax.swing.JFrame {

    /**
     * Creates new form petMenu
     */
    public petMenu() {
        initComponents();
        getContentPane().setBackground(Color.pink);  //set background color
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addPet = new javax.swing.JButton();
        searchPet = new javax.swing.JButton();
        updatePet = new javax.swing.JButton();
        services = new javax.swing.JButton();
        deletePet = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel1.setText("WHAT WOULD YOU LIKE TO DO?");

        addPet.setText("ADD PET");
        addPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPetActionPerformed(evt);
            }
        });

        searchPet.setText("SEARCH PETS");
        searchPet.setActionCommand("");
        searchPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPetActionPerformed(evt);
            }
        });

        updatePet.setText("UPDATE PET");
        updatePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePetActionPerformed(evt);
            }
        });

        services.setText("SELECT SERVICES");
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });

        deletePet.setText("DELETE PET");
        deletePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePetActionPerformed(evt);
            }
        });

        checkIn.setText("CHECK IN PET");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });

        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPet)
                    .addComponent(updatePet)
                    .addComponent(deletePet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPet)
                    .addComponent(services)
                    .addComponent(checkIn))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(logout))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPet)
                    .addComponent(searchPet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePet)
                    .addComponent(services))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePet)
                    .addComponent(checkIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPetActionPerformed
        // display add pet menu
        java.awt.EventQueue.invokeLater(() -> {
            new addPet().setVisible(true);
            dispose();
        });
        
    }//GEN-LAST:event_addPetActionPerformed

    private void updatePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePetActionPerformed
        //display update pet menu
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new updatePet().setVisible(true);
        });
    }//GEN-LAST:event_updatePetActionPerformed

    private void deletePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePetActionPerformed
        //display delete menu
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new deletePet().setVisible(true);
        });
    }//GEN-LAST:event_deletePetActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
        // display services menu
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new servicePet().setVisible(true);
        });
    }//GEN-LAST:event_servicesActionPerformed

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        // display pet check in menu
        java.awt.EventQueue.invokeLater(() -> {
            new checkIn().setVisible(true);
        });
    }//GEN-LAST:event_checkInActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // display user login screen
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new userLogin().setVisible(true);
        });
    }//GEN-LAST:event_logoutActionPerformed

    private void searchPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPetActionPerformed
        // display search menu to locate pet
         java.awt.EventQueue.invokeLater(() -> {
            new showAll().setVisible(true);
        });
    }//GEN-LAST:event_searchPetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new petMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPet;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton deletePet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton searchPet;
    private javax.swing.JButton services;
    private javax.swing.JButton updatePet;
    // End of variables declaration//GEN-END:variables
}
